version: "3.8"

services:
  food_app_test_db:
    image: postgres:14.2
    ports:
      - "5433:5432"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
