version: "3.8"

services:
  food_app:
    image: food-app:latest
    build: .
    ports:
      - "8080:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - ./:/app:ro
    depends_on:
      - db_migrations

  db_migrations:
    image: food-app:latest
    build: .
    command: ["poetry", "run", "python", "manage.py", "migrate"]
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    depends_on:
      - food_app_db
    volumes:
      - ./:/app:ro

  food_app_db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - food-app-data:/var/lib/postgresql/data

volumes:
  food-app-data:
