name: Linter and tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with pylint
      run: |
        poetry run poe lint
    - name: Unit tests
      run: |
        poetry run poe test
    - name: API tests
      run: |
        poetry run poe api_test
